---
slug: development
filename: example
title: Practical Developer Guide
subtitle: Modern Web Applications with angularjs and the play framwork
description: Modern Web Applications with angularjs and the play framwork
author: Frank Ittermann
copyright: 2014
uuid: bd8ef827-83a6-4b46-b3e6-257dd1d4898c
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
