---
slug: example
filename: example
title: Developer Guide
subtitle: Modern Web Applications with angularjs and the play framwork
description: Modern Web Applications with angularjs and the play framwork
author: Frank Ittermann
copyright: 2014
uuid: 13cfd7e1-dba6-40f2-b594-080704187370
pdf_preview_page_range: 1..30
epub_mobi_preview_chapter_range: 0..1
